<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2022-03-26 17:24:59 --> Severity: Warning --> mysqli::real_connect(): (HY000/1049): Unknown database 'pbo' C:\xampp\htdocs\hmvc_pbo\system\database\drivers\mysqli\mysqli_driver.php 135
ERROR - 2022-03-26 17:24:59 --> Unable to connect to the database
ERROR - 2022-03-26 17:27:06 --> 404 Page Not Found: /index
ERROR - 2022-03-26 17:27:12 --> Query error: Table 'pbo.user' doesn't exist - Invalid query: SELECT *
FROM `user`
WHERE `email` = 'saharuddin@gmail.com'
ERROR - 2022-03-26 17:27:12 --> Severity: error --> Exception: Call to a member function row_array() on bool C:\xampp\htdocs\hmvc_pbo\application\modules\login2\controllers\login2.php 31
ERROR - 2022-03-26 17:27:12 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of Error given, called in C:\xampp\htdocs\hmvc_pbo\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\hmvc_pbo\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\hmvc_pbo\system\core\Common.php(658): CI_Exceptions->show_exception(Object(Error))
#1 [internal function]: _exception_handler(Object(Error))
#2 {main}
  thrown C:\xampp\htdocs\hmvc_pbo\system\core\Exceptions.php 190
ERROR - 2022-03-26 17:27:59 --> Query error: Table 'pbo.user' doesn't exist - Invalid query: SELECT *
FROM `user`
WHERE `email` = 'saharuddin@gmail.com'
ERROR - 2022-03-26 17:27:59 --> Severity: error --> Exception: Call to a member function row_array() on bool C:\xampp\htdocs\hmvc_pbo\application\modules\login2\controllers\login2.php 31
ERROR - 2022-03-26 17:27:59 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of Error given, called in C:\xampp\htdocs\hmvc_pbo\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\hmvc_pbo\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\hmvc_pbo\system\core\Common.php(658): CI_Exceptions->show_exception(Object(Error))
#1 [internal function]: _exception_handler(Object(Error))
#2 {main}
  thrown C:\xampp\htdocs\hmvc_pbo\system\core\Exceptions.php 190
ERROR - 2022-03-26 17:28:56 --> 404 Page Not Found: /index
ERROR - 2022-03-26 17:29:10 --> Query error: Table 'pbo.user' doesn't exist - Invalid query: SELECT *
FROM `user`
WHERE `email` = 'saharuddin@gmail.com'
 LIMIT 1
ERROR - 2022-03-26 17:29:10 --> Severity: error --> Exception: Call to a member function num_rows() on bool C:\xampp\htdocs\hmvc_pbo\system\libraries\Form_validation.php 1134
ERROR - 2022-03-26 17:29:10 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of Error given, called in C:\xampp\htdocs\hmvc_pbo\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\hmvc_pbo\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\hmvc_pbo\system\core\Common.php(658): CI_Exceptions->show_exception(Object(Error))
#1 [internal function]: _exception_handler(Object(Error))
#2 {main}
  thrown C:\xampp\htdocs\hmvc_pbo\system\core\Exceptions.php 190
ERROR - 2022-03-26 17:29:37 --> 404 Page Not Found: ../modules/login2/controllers/Login2/index.php
ERROR - 2022-03-26 17:30:03 --> 404 Page Not Found: /index
ERROR - 2022-03-26 17:30:44 --> 404 Page Not Found: /index
ERROR - 2022-03-26 17:32:34 --> 404 Page Not Found: /index
ERROR - 2022-03-26 17:32:44 --> 404 Page Not Found: /index
ERROR - 2022-03-26 17:36:13 --> 404 Page Not Found: /index
ERROR - 2022-03-26 17:36:13 --> 404 Page Not Found: /index
ERROR - 2022-03-26 17:36:13 --> 404 Page Not Found: /index
ERROR - 2022-03-26 17:36:42 --> 404 Page Not Found: /index
ERROR - 2022-03-26 17:36:43 --> 404 Page Not Found: /index
ERROR - 2022-03-26 17:36:43 --> 404 Page Not Found: /index
